name: publish_master

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Logseq Publish
        uses: logseq/publish-spa@v0.3.0
        with:
          graph-directory: .
          theme-mode: light
          accent-color: "#ff0000"
      
      - name: Modify index.html
        run: |
          sed -i 's/<title>.*<\/title>/<title>anuraj.kool<\/title>/' www/index.html
          sed -i 's/<meta property="og:title".*>/<meta property="og:title" content="anuraj.kool">/' www/index.html
          sed -i 's|<link href="static/img/logo.png" type="image/png" rel="shortcut icon">|<link href="assets/at.png" type="image/png" rel="shortcut icon">|' www/index.html
          sed -i 's|<link href="static/img/logo.png" sizes="192x192" rel="shortcut icon">|<link href="assets/at.png" sizes="192x192" rel="shortcut icon">|' www/index.html
          sed -i 's|<link href="static/img/logo.png" rel="apple-touch-icon">|<link href="assets/at.png" rel="apple-touch-icon">|' www/index.html
          sed -i 's|<meta content="static/img/logo.png" property="og:image">|<meta content="assets/at.png" property="og:image">|' www/index.html
      - name: Add .nojekyll file
        run: touch www/.nojekyll

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: www
          clean: true
          clean-exclude: |
            CNAME
            .nojekyll